# .github/workflows/deploy.yml
name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main  # o la rama principal de tu repositorio

permissions:
  contents: write  # necesario para poder subir a gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # o la versión que uses

      - name: Install dependencies
        run: npm install

      - name: Build Astro site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

